/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as DashboardUploadRouteImport } from './routes/dashboard/upload'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardQueueRouteImport } from './routes/dashboard/queue'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardMattersRouteImport } from './routes/dashboard/matters'
import { Route as DashboardFilesRouteImport } from './routes/dashboard/files'
import { Route as DashboardClientsRouteImport } from './routes/dashboard/clients'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiQueueRouteImport } from './routes/api.queue'
import { Route as ApiProgressRouteImport } from './routes/api.progress'
import { Route as ApiNotificationsRouteImport } from './routes/api.notifications'
import { Route as ApiFilesRouteImport } from './routes/api.files'
import { Route as ApiEmailSettingsRouteImport } from './routes/api.email-settings'
import { Route as ApiDisconnectRouteImport } from './routes/api.disconnect'
import { Route as ApiContactsRouteImport } from './routes/api.contacts'
import { Route as mainAuthRouteRouteImport } from './routes/(main)/auth/route'
import { Route as DashboardContactsIndexRouteImport } from './routes/dashboard/contacts.index'
import { Route as DashboardContactsContactIdRouteImport } from './routes/dashboard/contacts.$contactId'
import { Route as ApiDropboxWebhookRouteImport } from './routes/api.dropbox.webhook'
import { Route as ApiDropboxFilesRouteImport } from './routes/api.dropbox.files'
import { Route as ApiDropboxDownloadRouteImport } from './routes/api.dropbox.download'
import { Route as ApiDocketwiseStatusRouteImport } from './routes/api.docketwise.status'
import { Route as ApiDocketwiseMattersRouteImport } from './routes/api.docketwise.matters'
import { Route as ApiDocketwiseContactsRouteImport } from './routes/api.docketwise.contacts'
import { Route as ApiContactsSyncRouteImport } from './routes/api.contacts.sync'
import { Route as ApiContactsContactIdRouteImport } from './routes/api.contacts.$contactId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as mainAuthSignUpRouteImport } from './routes/(main)/auth/sign-up'
import { Route as mainAuthSignInRouteImport } from './routes/(main)/auth/sign-in'
import { Route as mainAuthResetPasswordRouteImport } from './routes/(main)/auth/reset-password'
import { Route as mainAuthRequestPasswordResetRouteImport } from './routes/(main)/auth/request-password-reset'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardQueueRoute = DashboardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMattersRoute = DashboardMattersRouteImport.update({
  id: '/matters',
  path: '/matters',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFilesRoute = DashboardFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueRoute = ApiQueueRouteImport.update({
  id: '/api/queue',
  path: '/api/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressRoute = ApiProgressRouteImport.update({
  id: '/api/progress',
  path: '/api/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSettingsRoute = ApiEmailSettingsRouteImport.update({
  id: '/api/email-settings',
  path: '/api/email-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisconnectRoute = ApiDisconnectRouteImport.update({
  id: '/api/disconnect',
  path: '/api/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsRoute = ApiContactsRouteImport.update({
  id: '/api/contacts',
  path: '/api/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAuthRouteRoute = mainAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => mainRouteRoute,
} as any)
const DashboardContactsIndexRoute = DashboardContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContactsContactIdRoute =
  DashboardContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiDropboxWebhookRoute = ApiDropboxWebhookRouteImport.update({
  id: '/api/dropbox/webhook',
  path: '/api/dropbox/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDropboxFilesRoute = ApiDropboxFilesRouteImport.update({
  id: '/api/dropbox/files',
  path: '/api/dropbox/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDropboxDownloadRoute = ApiDropboxDownloadRouteImport.update({
  id: '/api/dropbox/download',
  path: '/api/dropbox/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocketwiseStatusRoute = ApiDocketwiseStatusRouteImport.update({
  id: '/api/docketwise/status',
  path: '/api/docketwise/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocketwiseMattersRoute = ApiDocketwiseMattersRouteImport.update({
  id: '/api/docketwise/matters',
  path: '/api/docketwise/matters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocketwiseContactsRoute = ApiDocketwiseContactsRouteImport.update({
  id: '/api/docketwise/contacts',
  path: '/api/docketwise/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsSyncRoute = ApiContactsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiContactsContactIdRoute = ApiContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAuthSignUpRoute = mainAuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => mainAuthRouteRoute,
} as any)
const mainAuthSignInRoute = mainAuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => mainAuthRouteRoute,
} as any)
const mainAuthResetPasswordRoute = mainAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => mainAuthRouteRoute,
} as any)
const mainAuthRequestPasswordResetRoute =
  mainAuthRequestPasswordResetRouteImport.update({
    id: '/request-password-reset',
    path: '/request-password-reset',
    getParentRoute: () => mainAuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth': typeof mainAuthRouteRouteWithChildren
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/disconnect': typeof ApiDisconnectRoute
  '/api/email-settings': typeof ApiEmailSettingsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/queue': typeof ApiQueueRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/matters': typeof DashboardMattersRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/': typeof mainIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/request-password-reset': typeof mainAuthRequestPasswordResetRoute
  '/auth/reset-password': typeof mainAuthResetPasswordRoute
  '/auth/sign-in': typeof mainAuthSignInRoute
  '/auth/sign-up': typeof mainAuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/contacts/$contactId': typeof ApiContactsContactIdRoute
  '/api/contacts/sync': typeof ApiContactsSyncRoute
  '/api/docketwise/contacts': typeof ApiDocketwiseContactsRoute
  '/api/docketwise/matters': typeof ApiDocketwiseMattersRoute
  '/api/docketwise/status': typeof ApiDocketwiseStatusRoute
  '/api/dropbox/download': typeof ApiDropboxDownloadRoute
  '/api/dropbox/files': typeof ApiDropboxFilesRoute
  '/api/dropbox/webhook': typeof ApiDropboxWebhookRoute
  '/dashboard/contacts/$contactId': typeof DashboardContactsContactIdRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof mainAuthRouteRouteWithChildren
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/disconnect': typeof ApiDisconnectRoute
  '/api/email-settings': typeof ApiEmailSettingsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/queue': typeof ApiQueueRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/matters': typeof DashboardMattersRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/': typeof mainIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/request-password-reset': typeof mainAuthRequestPasswordResetRoute
  '/auth/reset-password': typeof mainAuthResetPasswordRoute
  '/auth/sign-in': typeof mainAuthSignInRoute
  '/auth/sign-up': typeof mainAuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/contacts/$contactId': typeof ApiContactsContactIdRoute
  '/api/contacts/sync': typeof ApiContactsSyncRoute
  '/api/docketwise/contacts': typeof ApiDocketwiseContactsRoute
  '/api/docketwise/matters': typeof ApiDocketwiseMattersRoute
  '/api/docketwise/status': typeof ApiDocketwiseStatusRoute
  '/api/dropbox/download': typeof ApiDropboxDownloadRoute
  '/api/dropbox/files': typeof ApiDropboxFilesRoute
  '/api/dropbox/webhook': typeof ApiDropboxWebhookRoute
  '/dashboard/contacts/$contactId': typeof DashboardContactsContactIdRoute
  '/dashboard/contacts': typeof DashboardContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/(main)/auth': typeof mainAuthRouteRouteWithChildren
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/disconnect': typeof ApiDisconnectRoute
  '/api/email-settings': typeof ApiEmailSettingsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/queue': typeof ApiQueueRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/files': typeof DashboardFilesRoute
  '/dashboard/matters': typeof DashboardMattersRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/(main)/': typeof mainIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/(main)/auth/request-password-reset': typeof mainAuthRequestPasswordResetRoute
  '/(main)/auth/reset-password': typeof mainAuthResetPasswordRoute
  '/(main)/auth/sign-in': typeof mainAuthSignInRoute
  '/(main)/auth/sign-up': typeof mainAuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/contacts/$contactId': typeof ApiContactsContactIdRoute
  '/api/contacts/sync': typeof ApiContactsSyncRoute
  '/api/docketwise/contacts': typeof ApiDocketwiseContactsRoute
  '/api/docketwise/matters': typeof ApiDocketwiseMattersRoute
  '/api/docketwise/status': typeof ApiDocketwiseStatusRoute
  '/api/dropbox/download': typeof ApiDropboxDownloadRoute
  '/api/dropbox/files': typeof ApiDropboxFilesRoute
  '/api/dropbox/webhook': typeof ApiDropboxWebhookRoute
  '/dashboard/contacts/$contactId': typeof DashboardContactsContactIdRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/auth'
    | '/api/contacts'
    | '/api/disconnect'
    | '/api/email-settings'
    | '/api/files'
    | '/api/notifications'
    | '/api/progress'
    | '/api/queue'
    | '/api/upload'
    | '/dashboard/clients'
    | '/dashboard/files'
    | '/dashboard/matters'
    | '/dashboard/notifications'
    | '/dashboard/queue'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/'
    | '/dashboard/'
    | '/auth/request-password-reset'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/api/auth/$'
    | '/api/contacts/$contactId'
    | '/api/contacts/sync'
    | '/api/docketwise/contacts'
    | '/api/docketwise/matters'
    | '/api/docketwise/status'
    | '/api/dropbox/download'
    | '/api/dropbox/files'
    | '/api/dropbox/webhook'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/api/contacts'
    | '/api/disconnect'
    | '/api/email-settings'
    | '/api/files'
    | '/api/notifications'
    | '/api/progress'
    | '/api/queue'
    | '/api/upload'
    | '/dashboard/clients'
    | '/dashboard/files'
    | '/dashboard/matters'
    | '/dashboard/notifications'
    | '/dashboard/queue'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/'
    | '/dashboard'
    | '/auth/request-password-reset'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/api/auth/$'
    | '/api/contacts/$contactId'
    | '/api/contacts/sync'
    | '/api/docketwise/contacts'
    | '/api/docketwise/matters'
    | '/api/docketwise/status'
    | '/api/dropbox/download'
    | '/api/dropbox/files'
    | '/api/dropbox/webhook'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/contacts'
  id:
    | '__root__'
    | '/(main)'
    | '/dashboard'
    | '/(main)/auth'
    | '/api/contacts'
    | '/api/disconnect'
    | '/api/email-settings'
    | '/api/files'
    | '/api/notifications'
    | '/api/progress'
    | '/api/queue'
    | '/api/upload'
    | '/dashboard/clients'
    | '/dashboard/files'
    | '/dashboard/matters'
    | '/dashboard/notifications'
    | '/dashboard/queue'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/(main)/'
    | '/dashboard/'
    | '/(main)/auth/request-password-reset'
    | '/(main)/auth/reset-password'
    | '/(main)/auth/sign-in'
    | '/(main)/auth/sign-up'
    | '/api/auth/$'
    | '/api/contacts/$contactId'
    | '/api/contacts/sync'
    | '/api/docketwise/contacts'
    | '/api/docketwise/matters'
    | '/api/docketwise/status'
    | '/api/dropbox/download'
    | '/api/dropbox/files'
    | '/api/dropbox/webhook'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiContactsRoute: typeof ApiContactsRouteWithChildren
  ApiDisconnectRoute: typeof ApiDisconnectRoute
  ApiEmailSettingsRoute: typeof ApiEmailSettingsRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiProgressRoute: typeof ApiProgressRoute
  ApiQueueRoute: typeof ApiQueueRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocketwiseContactsRoute: typeof ApiDocketwiseContactsRoute
  ApiDocketwiseMattersRoute: typeof ApiDocketwiseMattersRoute
  ApiDocketwiseStatusRoute: typeof ApiDocketwiseStatusRoute
  ApiDropboxDownloadRoute: typeof ApiDropboxDownloadRoute
  ApiDropboxFilesRoute: typeof ApiDropboxFilesRoute
  ApiDropboxWebhookRoute: typeof ApiDropboxWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/queue': {
      id: '/dashboard/queue'
      path: '/queue'
      fullPath: '/dashboard/queue'
      preLoaderRoute: typeof DashboardQueueRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/matters': {
      id: '/dashboard/matters'
      path: '/matters'
      fullPath: '/dashboard/matters'
      preLoaderRoute: typeof DashboardMattersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/files': {
      id: '/dashboard/files'
      path: '/files'
      fullPath: '/dashboard/files'
      preLoaderRoute: typeof DashboardFilesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue': {
      id: '/api/queue'
      path: '/api/queue'
      fullPath: '/api/queue'
      preLoaderRoute: typeof ApiQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress': {
      id: '/api/progress'
      path: '/api/progress'
      fullPath: '/api/progress'
      preLoaderRoute: typeof ApiProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email-settings': {
      id: '/api/email-settings'
      path: '/api/email-settings'
      fullPath: '/api/email-settings'
      preLoaderRoute: typeof ApiEmailSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/disconnect': {
      id: '/api/disconnect'
      path: '/api/disconnect'
      fullPath: '/api/disconnect'
      preLoaderRoute: typeof ApiDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts': {
      id: '/api/contacts'
      path: '/api/contacts'
      fullPath: '/api/contacts'
      preLoaderRoute: typeof ApiContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth': {
      id: '/(main)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof mainAuthRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/dashboard/contacts/': {
      id: '/dashboard/contacts/'
      path: '/contacts'
      fullPath: '/dashboard/contacts/'
      preLoaderRoute: typeof DashboardContactsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contacts/$contactId': {
      id: '/dashboard/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/dashboard/contacts/$contactId'
      preLoaderRoute: typeof DashboardContactsContactIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/dropbox/webhook': {
      id: '/api/dropbox/webhook'
      path: '/api/dropbox/webhook'
      fullPath: '/api/dropbox/webhook'
      preLoaderRoute: typeof ApiDropboxWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dropbox/files': {
      id: '/api/dropbox/files'
      path: '/api/dropbox/files'
      fullPath: '/api/dropbox/files'
      preLoaderRoute: typeof ApiDropboxFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dropbox/download': {
      id: '/api/dropbox/download'
      path: '/api/dropbox/download'
      fullPath: '/api/dropbox/download'
      preLoaderRoute: typeof ApiDropboxDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docketwise/status': {
      id: '/api/docketwise/status'
      path: '/api/docketwise/status'
      fullPath: '/api/docketwise/status'
      preLoaderRoute: typeof ApiDocketwiseStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docketwise/matters': {
      id: '/api/docketwise/matters'
      path: '/api/docketwise/matters'
      fullPath: '/api/docketwise/matters'
      preLoaderRoute: typeof ApiDocketwiseMattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docketwise/contacts': {
      id: '/api/docketwise/contacts'
      path: '/api/docketwise/contacts'
      fullPath: '/api/docketwise/contacts'
      preLoaderRoute: typeof ApiDocketwiseContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts/sync': {
      id: '/api/contacts/sync'
      path: '/sync'
      fullPath: '/api/contacts/sync'
      preLoaderRoute: typeof ApiContactsSyncRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/contacts/$contactId': {
      id: '/api/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/api/contacts/$contactId'
      preLoaderRoute: typeof ApiContactsContactIdRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth/sign-up': {
      id: '/(main)/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof mainAuthSignUpRouteImport
      parentRoute: typeof mainAuthRouteRoute
    }
    '/(main)/auth/sign-in': {
      id: '/(main)/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof mainAuthSignInRouteImport
      parentRoute: typeof mainAuthRouteRoute
    }
    '/(main)/auth/reset-password': {
      id: '/(main)/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof mainAuthResetPasswordRouteImport
      parentRoute: typeof mainAuthRouteRoute
    }
    '/(main)/auth/request-password-reset': {
      id: '/(main)/auth/request-password-reset'
      path: '/request-password-reset'
      fullPath: '/auth/request-password-reset'
      preLoaderRoute: typeof mainAuthRequestPasswordResetRouteImport
      parentRoute: typeof mainAuthRouteRoute
    }
  }
}

interface mainAuthRouteRouteChildren {
  mainAuthRequestPasswordResetRoute: typeof mainAuthRequestPasswordResetRoute
  mainAuthResetPasswordRoute: typeof mainAuthResetPasswordRoute
  mainAuthSignInRoute: typeof mainAuthSignInRoute
  mainAuthSignUpRoute: typeof mainAuthSignUpRoute
}

const mainAuthRouteRouteChildren: mainAuthRouteRouteChildren = {
  mainAuthRequestPasswordResetRoute: mainAuthRequestPasswordResetRoute,
  mainAuthResetPasswordRoute: mainAuthResetPasswordRoute,
  mainAuthSignInRoute: mainAuthSignInRoute,
  mainAuthSignUpRoute: mainAuthSignUpRoute,
}

const mainAuthRouteRouteWithChildren = mainAuthRouteRoute._addFileChildren(
  mainAuthRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainAuthRouteRoute: typeof mainAuthRouteRouteWithChildren
  mainIndexRoute: typeof mainIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainAuthRouteRoute: mainAuthRouteRouteWithChildren,
  mainIndexRoute: mainIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardFilesRoute: typeof DashboardFilesRoute
  DashboardMattersRoute: typeof DashboardMattersRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardQueueRoute: typeof DashboardQueueRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardContactsContactIdRoute: typeof DashboardContactsContactIdRoute
  DashboardContactsIndexRoute: typeof DashboardContactsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardFilesRoute: DashboardFilesRoute,
  DashboardMattersRoute: DashboardMattersRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardQueueRoute: DashboardQueueRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardContactsContactIdRoute: DashboardContactsContactIdRoute,
  DashboardContactsIndexRoute: DashboardContactsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ApiContactsRouteChildren {
  ApiContactsContactIdRoute: typeof ApiContactsContactIdRoute
  ApiContactsSyncRoute: typeof ApiContactsSyncRoute
}

const ApiContactsRouteChildren: ApiContactsRouteChildren = {
  ApiContactsContactIdRoute: ApiContactsContactIdRoute,
  ApiContactsSyncRoute: ApiContactsSyncRoute,
}

const ApiContactsRouteWithChildren = ApiContactsRoute._addFileChildren(
  ApiContactsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiContactsRoute: ApiContactsRouteWithChildren,
  ApiDisconnectRoute: ApiDisconnectRoute,
  ApiEmailSettingsRoute: ApiEmailSettingsRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiProgressRoute: ApiProgressRoute,
  ApiQueueRoute: ApiQueueRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocketwiseContactsRoute: ApiDocketwiseContactsRoute,
  ApiDocketwiseMattersRoute: ApiDocketwiseMattersRoute,
  ApiDocketwiseStatusRoute: ApiDocketwiseStatusRoute,
  ApiDropboxDownloadRoute: ApiDropboxDownloadRoute,
  ApiDropboxFilesRoute: ApiDropboxFilesRoute,
  ApiDropboxWebhookRoute: ApiDropboxWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
